"""Add test table

Revision ID: 0c90d00d2301
Revises: 
Create Date: 2019-11-16 22:33:23.656958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c90d00d2301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
   # op.add_column('preference', sa.Column('latitude', sa.Float(), nullable=True))
    #op.add_column('preference', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('preference', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preference', 'longitude')
    op.drop_column('preference', 'latitude')
    op.drop_table('test_table')
    # ### end Alembic commands ###



