"""empty message

Revision ID: 00240aa04f86
Revises: d2df465896cc
Create Date: 2019-12-06 13:39:47.830331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00240aa04f86'
down_revision = 'd2df465896cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'description')
    # ### end Alembic commands ###
