"""empty message

Revision ID: ffff2595e764
Revises: 8172f70bf822
Create Date: 2019-12-03 19:30:26.723561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffff2595e764'
down_revision = '8172f70bf822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferenceCategory',
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['preference_id'], ['preference.preference_id'], ),
    sa.PrimaryKeyConstraint('preference_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferenceCategory')
    # ### end Alembic commands ###
